import "./globals.css"

import CmsNavbar from "@/app/components/CmsNavbar"
import Provider from "@/app/utils/Provider"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <CmsNavbar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
